name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Run linting
      run: npm run lint
      
    - name: Run build
      run: npm run build
      
    - name: Validate manifest
      run: |
        # Basic manifest validation
        node -e "
          const manifest = require('./manifest.json');
          if (!manifest.name || !manifest.version || !manifest.manifest_version) {
            process.exit(1);
          }
          console.log('Manifest validation passed');
        "
        
    - name: Check file structure
      run: |
        # Verify required extension files exist
        test -f manifest.json || (echo 'manifest.json is required' && exit 1)
        test -f background.js || (echo 'background.js is required' && exit 1)
        test -d popup || (echo 'popup directory is required' && exit 1)
        test -d content || (echo 'content directory is required' && exit 1)
        test -d icons || (echo 'icons directory is required' && exit 1)
        echo 'File structure validation passed'

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Run tests
      run: npm test || echo "No tests configured yet"
      
    - name: Security audit
      run: npm audit --audit-level moderate
      continue-on-error: true